more_useful_clean_code
Drishtantranjan/Awesome-Navigation-Bar pull request #1
Opened 2024-02-19 07:10 UTC by AvniErtas

Yesterday I saw your package in Linkedln and I decided to use in my project. But when I try to use I found some issues for users. I decided to upgrade with using more clean code and sheet name change option. Also we can add later sheet count option (can be changed by user)

Best Regards,
Avni

2024-02-24 05:13 UTC, Drishtantranjan requested changes
Please look into the reviews I have mentioned. Make sure to do the changes accordingly and submit the PR again.

2024-02-24 05:13 UTC, Drishtantranjan commented on lib/src/navigationBar.dart
> +      activeIcon: Image.asset(
assets will not get loaded by using this way

2024-02-24 05:13 UTC, Drishtantranjan commented on lib/src/navigationBar.dart
> +    "assets/home/ic_home.png",
home.png does not exist as asset

2024-02-25 17:20 UTC, merged

2024-02-25 17:28 UTC, AvniErtas commented
Hi,

Sorry for late answer but right now here is Sunday and honestly I have to spend time with my family so I don't have time to fix it right now but as soon as possible I will check it.

Best Regards,
Avni

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________
From: Drishtant Ranjan Srivastava ***@***.***>
Sent: Sunday, February 25, 2024 8:21:03 PM
To: Drishtantranjan/Awesome-Navigation-Bar ***@***.***>
Cc: AvniErtas ***@***.***>; Author ***@***.***>
Subject: Re: [Drishtantranjan/Awesome-Navigation-Bar] more_useful_clean_code (PR #1)


Merged #1<https://github.com/Drishtantranjan/Awesome-Navigation-Bar/pull/1> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/Drishtantranjan/Awesome-Navigation-Bar/pull/1#event-11913468594>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AODAMPS4HUJXHTTVUOBRXWDYVNXH7AVCNFSM6AAAAABDO5NEXCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRHEYTGNBWHA2TSNA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>